### ISSUE TITLE
会不会有审核风险

### ISSUE THREAD

**Issue by ustcqidi** [LiuShuoyu/HybirdWKWebVIew#2]
如题。

用到了一些私有API，会不会有审核风险？

**Comment by LiuShuoyu** [comment]
你好，我们公司一直在用。没有因为这个原因被拒绝过。

**Comment by ustcqidi** [comment]
hello, 如果开启了ATS，这个拦截还有效么？

**Comment by LiuShuoyu** [comment]
no problem

**Comment by LiuShuoyu** [comment]
如果有问题， 请联系我的微信476804765。 大家一起讨论学习

**Comment by zhengwu0591** [comment]
你好，都说苹果一查到私有API就会下架的。为什么你们使用私有API没有事呢？这是一种幸运吗？哈哈

**Comment by LiuShuoyu** [comment]
你好，我们公司一直在用。没有因为这个原因被拒绝过。而且感觉WK也是趋势， 苹果应该不会拒绝
